import os
import time
from google import genai

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

OUTPUT_DIR = os.path.join("client", "public", "cards")
os.makedirs(OUTPUT_DIR, exist_ok=True)

PROMPTS = [
    # 01 Профессии
    ("profession-vrach-khirurg.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a surgical scalpel crossed with a heart-rate pulse line."),
    ("profession-inzhener-gidrotekhnik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a water pipe valve wheel with dripping water droplet."),
    ("profession-santekhnik-elektrik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a wrench crossed with a lightning bolt."),
    ("profession-agronom-bioekolog.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a sprouting seedling growing inside a glass dome."),
    ("profession-fizik-yadershchik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an atom symbol with a radiation trefoil at its core."),
    ("profession-pozharnyy-spasatel.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a fire helmet with an axe behind it."),
    ("profession-programmist-robototekhnik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a robotic gear with a binary code bracket around it."),
    ("profession-psikhoterapevt.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a human head silhouette with a calm spiral inside it."),
    ("profession-povar-tekhnolog.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a chef knife crossed with a ladle."),
    ("profession-veterinar-zoolog.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a paw print inside a medical cross."),
    ("profession-ofitser-takticheskoy-razvedki.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a pair of binoculars over a tactical map grid."),
    ("profession-stroitel-kamenshchik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a trowel resting on a stack of bricks."),
    ("profession-khimik-laborant.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a bubbling laboratory flask with a molecule symbol."),
    ("profession-mekhanik-avtotransporta.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a wrench crossed with a piston gear."),
    ("profession-uchitel-nachalnykh-klassov.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an open book with a pencil standing upright on it."),

    # 02 Здоровье
    ("health-idealno-zdorov.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a bold checkmark inside a heartbeat pulse line."),
    ("health-legkaya-astma.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple asthma inhaler icon with a soft breath wave."),
    ("health-sakharnyy-diabet-1-tip.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a small insulin vial next to a blood-drop droplet icon."),
    ("health-chastichnaya-glukhota.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an ear icon with one side of its sound waves fading out."),
    ("health-khronicheskiy-gastrit.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a minimal stomach outline icon with a warning spark."),
    ("health-miopiya-3-5.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a pair of round eyeglasses with one lens slightly blurred."),
    ("health-daltonizm.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple color-blindness test dot pattern circle."),
    ("health-besplodie.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a minimal empty seed-pod outline icon, abstract and non-clinical."),
    ("health-vysokiy-immunitet-k-infektsiyam.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a shield icon deflecting small virus-cell shapes."),
    ("health-perelom-ruki-v-gipse.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a forearm icon wrapped in a plaster cast."),

    # 03 Биология
    ("biology-muzhchina-24.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple male bust silhouette icon, young adult posture."),
    ("biology-zhenshchina-26.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple female bust silhouette icon, young adult posture."),
    ("biology-muzhchina-35.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple male bust silhouette icon, athletic build."),
    ("biology-zhenshchina-29.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple female bust silhouette icon, alert confident posture."),
    ("biology-muzhchina-42.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple male bust silhouette icon with faint temple grey streak."),
    ("biology-zhenshchina-38-mat.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple female bust silhouette icon with a small heart mark near the chest."),
    ("biology-muzhchina-19.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple slim male bust silhouette icon, youthful posture."),
    ("biology-zhenshchina-22-sportsmenka.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a simple female bust silhouette icon with a small laurel/sport mark."),

    # 04 Хобби
    ("hobby-okhota-i-rybalka.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a fishing hook crossed with a hunting arrow."),
    ("hobby-strelba-iz-luka.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a drawn bow and arrow aimed at a small target."),
    ("hobby-radiolyubitelstvo.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a vintage shortwave radio with visible signal waves."),
    ("hobby-pervaya-pomoshch-i-dezhurstvo.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a medical cross inside a stopwatch shape."),
    ("hobby-sadovodstvo-i-gidroponika.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a plant sprouting from a hydroponic tray."),
    ("hobby-igra-na-gitare-i-penie.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an acoustic guitar with a musical note above it."),
    ("hobby-shakhmaty-i-strategiya.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a chess knight piece on a checkered tile."),
    ("hobby-rukopashnyy-boy-sambo.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: two crossed fists in a combat stance icon."),
    ("hobby-shite-i-remont-odezhdy.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a needle threading through fabric with a small stitch line."),
    ("hobby-stolyarnoe-delo.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a wood plane resting on a curl of wood shaving."),

    # 05 Черты характера
    ("trait-optimist.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a small bright sun rising over a flat horizon line."),
    ("trait-khladnokrovnyy-analitik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a geometric crystal shape with a single cool spark inside."),
    ("trait-liderskie-kachestva.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a minimal crown resting above a compass needle."),
    ("trait-trudogolik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a gear wheel fused with a running clock face."),
    ("trait-klaustrofobiya.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a narrow doorway frame closing inward, tense and tight."),
    ("trait-pedant.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a checklist with every box perfectly ticked, ruler beside it."),
    ("trait-skromnyy-i-molchalivyy.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a closed mouth icon with a single quiet dot above it."),
    ("trait-paranoik.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a single wide eye inside a warning triangle."),

    # 06 Багаж
    ("baggage-nabor-khirurgicheskikh-instrumentov.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an open surgical instrument case with scalpel and forceps."),
    ("baggage-kanistra-ochishchennoy-vody-20-l.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a sealed metal water canister with a droplet mark."),
    ("baggage-armeyskiy-sukhoy-paek-na-1-mesyats.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a stamped military ration box with a fork icon."),
    ("baggage-solnechnaya-panel-100w-pauerbank.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a foldable solar panel with a small power bank beside it."),
    ("baggage-schetchik-geygera-dozimetr.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a handheld Geiger counter device with a radiation trefoil."),
    ("baggage-nabor-semyan-ovoshchey-i-zlakov.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a sealed seed packet with a wheat sprig printed on it."),
    ("baggage-moshchnaya-benzopila-kanistra-topliva.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a chainsaw resting beside a fuel canister."),
    ("baggage-nabor-filtrov-dlya-ochistki-vody.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: stacked cylindrical water filter cartridges."),
    ("baggage-elektroakusticheskaya-gitara.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an electro-acoustic guitar with a cable jack."),
    ("baggage-skladnaya-yashchik-instrumentov-mekhanika.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: an open mechanic toolbox with wrenches and a screwdriver."),

    # 07 Секреты
    ("secret-sluzhil-v-spetsnaze.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a plain military dog tag with a covert unit chevron."),
    ("secret-taynyy-immunitet.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a glowing DNA helix protected inside a shield outline."),
    ("secret-skrytyy-zapas-oruzhiya.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a padlocked crate with a faint rifle silhouette shadow."),
    ("secret-falshivyy-diplom.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a diploma scroll with a cracked wax seal."),
    ("secret-spas-5-chelovek.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a single reaching hand pulling another hand up from below."),
    ("secret-znaet-inzhenernyy-plan-bunkera.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a rolled blueprint schematic with a bunker cross-section."),

    # 08 Действия
    ("action-vtoroy-shans.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a circular rewind arrow wrapped around a ballot box."),
    ("action-udvoenie-golosa.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: two overlapping checkmarks inside a ballot icon."),
    ("action-obmen-professiey.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: two crossed swap arrows between a wrench and a stethoscope."),
    ("action-proverka-zdorovya.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a magnifying glass hovering over a heartbeat pulse line."),
    ("action-immunitet-raunda.png", "Create a single square (1:1) card icon illustration in a dark, post-apocalyptic industrial poster style: a muted charcoal-dark background, one warm amber-orange accent color and everything else desaturated, a flat stenciled screen-print look with light grain and scuff texture, no gradients, no photorealism, and no text, letters, numbers or watermarks anywhere in the image. The centered subject is: a glowing shield icon with a small lock at its center.")
]

def generate_all():
    print(f"Starting batch generation of {len(PROMPTS)} cards...")
    for idx, (filename, prompt) in enumerate(PROMPTS, 1):
        target_path = os.path.join(OUTPUT_DIR, filename)
        if os.path.exists(target_path):
            print(f"[{idx}/{len(PROMPTS)}] Skipping {filename} (already exists)")
            continue

        print(f"[{idx}/{len(PROMPTS)}] Generating {filename}...")
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash-image',
                contents=prompt,
            )
            saved = False
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    with open(target_path, "wb") as f:
                        f.write(part.inline_data.data)
                    print(f"  Saved {filename}")
                    saved = True
                    break
            if not saved:
                print(f"  Failed {filename}: No image data in response")
            time.sleep(2)
        except Exception as e:
            print(f"  Failed {filename}: {e}")
            time.sleep(2)

if __name__ == "__main__":
    generate_all()
